### ISSUE TITLE
脚注番号前後のアキ対応

### ISSUE THREAD

**Issue by kmaed** [texjporg/ptex-texmf#2]
aa1872b で脚注番号前後の和文文字との間にアキが入る問題に対応するコードを入れました．
- この変更による副作用
- バージョン番号について

など，なにかあればお知らせ下さい．バージョン番号はオリジナルを踏襲して v1.2a -> v1.2b とかしていますが，変えた方がよいような気もします．私個人で作るものならこの際日付だけにしてしまいますが……．

一応 platex.fmt の作り方ですが，tex/platex/base/ をローカルの TEXMF ツリーに置いて，

```
$ fmtutil --byfmt platex
```

とします．これで（TeX LIve 2015 なら）~/.texlive2015/texmf-var/web2c/eptex/ に platex.fmt ができると思います．元の TeX Live のものに戻したいときは，単純にこの platex.fmt を削除すればOKです．

**Comment by aminophen** [comment]
bd6284c で \CheckSum を修正しました。

＃ この \CheckSum は「登場する `\` の数」だった気がしますが，簡単に算出するには make してエラーメッセージを見る（もしくは \CheckSum{0} にしておいて警告メッセージから読み取る）しかないでしょうか？

**Comment by kmaed** [comment]
\CheckSum のことをすっかり忘れていました．ありがとうございました．

**Comment by aminophen** [comment]
細かいですが，[r28720](http://www.tug.org/svn/texlive?view=revision&revision=28720) は ptex-base.ch に対するパッチなので e-pTeX にかぎらず pTeX 本体です。\changes のメッセージをいまから修正しておきます。 (a12fc94)

> 一応 platex.fmt の作り方ですが

W32TeX では `$TEXMFVAR` が定義されていないので，

```
$ fmtutil --byfmt platex
```

を実行すると `$TEXMFMAIN/web2c/engine` すなわち `$TEXMFDIST/web2c/eptex` に platex.fmt が入ってしまい，元のものを上書きしてしまいます（ちなみに fmtutil-sys は存在しません）。これが嫌な場合は `--fmtdir` で `$TEXMFLOCAL` 以下を指定する必要がありそうです。

**Comment by aminophen** [comment]
> 脚注番号前後の和文文字との間にアキが入る問題

これと根が同じかもしれない現象を確認しましたので、ここにつけます。

``` tex
\documentclass{jsarticle}
\begin{document}
\fboxsep0pt

{\TeX}は\begin{tabular}[c]{l}ほげ\\なんとか\end{tabular}アレ。

{\TeX}は\fbox{\begin{tabular}[c]{l}ほげ\\なんとか\end{tabular}}アレ。

\end{document}
```

これを TL2015 と TL2012 の pTeX で処理すると以下のようになります。

![tabular-xkanjiskip-03](https://cloud.githubusercontent.com/assets/9957466/13373077/8bc3b8e2-dda0-11e5-9bd9-aa8a60dbc012.png)

```
e-pTeX 3.14159265-p3.7-150805-2.6 (sjis) (TeX Live 2015/W32TeX)
e-pTeX 3.1415926-p3.3-110825-2.5 (utf8.sjis) (TeX Live 2012/W32TeX)
```

tabular 環境の前後に TL2015 のみ xkanjiskip が入っていることがわかります。しかし、\fbox で囲むとなぜか元に戻ります。これは期待どおりなのでしょうか？

**Comment by aminophen** [comment]
仮にこれを修正するとした場合：脚注番号前後のアキ対策にならい、LaTeX 本家 lttab.dtx の tabular 環境の定義部分のコードを持ってきて

``` tex
\def\endtabular{\crcr\egroup\egroup $\egroup \hbox{}}    % 最後の \hbox{} を追加
\def\@tabular{\leavevmode \hbox{}\hbox \bgroup $\let\@acol\@tabacol    % 最初の \hbox{} を追加
   \let\@classz\@tabclassz
   \let\@classiv\@tabclassiv \let\\\@tabularcr\@tabarray}
```

とすると \xkanjiskip 由来のアキは消えます。tabular だけでなく \parbox[c] も同様の現象が起きます ([Twitter](https://twitter.com/zr_tex8r/status/703572325967405056)) ので、この類の環境ひとつひとつに \hbox{} を入れて対処することになりそうです。対象はこれから調べます。

なお、これらの環境は plext.sty でも組方向オプション (y,t,z) を追加するために拡張されていますので、最終的には同様の変更を plext.dtx にも施すことになります。ただ、組方向オプションの拡張を plext.sty にゆだねず、plcore.ltx に入れてしまえば一本化できるため、これも個人的には視野に入れたいです。

**Comment by aminophen** [comment]
内部的に `$ ... $` が使われていて、「2013年の pTeX の \xkanjiskip に関する変更の影響を受けたもの」、または「2012年以前からではあるが不自然な \xkanjiskip が入るもの」を列挙していきます。「脚注番号」は既に対処済みなので、それ以外は：
- lttab.dtx で定義されているもの：
  - tabular 環境
- ltboxes.dtx で定義されているもの：
  - minipage 環境 ← これは2012年以前から。
    （下の \parbox[c] を直せば自動的に直るが、plext.dtx で再定義されることに注意）
  - \parbox[c]{…} ← これは2012年以前から。
  - \underline{…} ← これは2012年以前から。

ほかにもあるでしょうか。

**Comment by h-kitagawa** [comment]
3327a47189adf1ba4a71d372de88a9ca35659483 で tabular, parbox, underline を直しました．

> ただ、組方向オプションの拡張を plext.sty にゆだねず、plcore.ltx に入れてしまえば一本化できるため、これも個人的には視野に入れたいです。

plext.sty による修正は他のパッケージと競合することがあります．例えば plext.sty → array.sty の順番でロードすると

```
\begin{tabular}<t>{ll}ほげ\\ABCDEF\end{tabular}%
```

からは

```
! Package array Error: <{..} at wrong position: changed to !{..}
```

というエラーが出ます（LuaTeX-ja 内の lltjext.sty では同様の事情に独自対応しています）．こういうことを考えると，フォーマット化はやりすぎかと思います．

**Comment by aminophen** [comment]
> tabular, parbox, underline を直しました．

ありがとうございます。

> plext.sty による修正は他のパッケージと競合することがあります．

そういう事情があるのですね。では現状維持としましょう。[plext_test](https://github.com/h-kitagawa/plext_test) も確認しました。
