### ISSUE TITLE
tabular の垂直位置，縦組クラスでの overfull 

### ISSUE THREAD

**Issue by aminophen** [texjporg/ptex-texmf#3]
TeX フォーラムの過去トピックで，pLaTeX の挙動に関するコメントで私が拾えたものです。
- plext.sty の有無で tabular の垂直位置が変わる ([forum:1355](http://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=1355))
- 縦組クラスでの overfull 警告 ([forum:1442](http://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=1442))

これらは手つかずとなっています。

**Comment by h-kitagawa** [comment]
> 縦組クラスでの overfull 警告 (forum:1442)

f67085a で LuaTeX-ja と同様の対処をしました．

**Comment by aminophen** [comment]
pldoc.pdf をつくろうとしたところ，\changes の中身がよくないらしく

```
) [137] (./plpatch.ltx) [138] (./pldoc.gls(guessed encoding: Shift_JIS = sjis) [
139] [140] [141] [142] [143]
! Missing number, treated as zero.
<to be read again>
                   @
l.423 ^^I^^I\\vskip -\dimen @
                             |が縦組モードでは無効になっていたので修正{35}
?
```

で止まります。しかし直し方が分かりません…

**Comment by h-kitagawa** [comment]
> pldoc.pdf をつくろうとしたところ，\changes の中身がよくないらしく

すみません，\changes の引数の中で verbatim | ... | を使っていました．f467ac5 ではどうでしょうか．

**Comment by aminophen** [comment]
> f467ac5 ではどうでしょうか．

今度は make 通りました。ありがとうございます。

**Comment by h-kitagawa** [comment]
> plext.sty の有無で tabular の垂直位置が変わる (forum:1355)

[plext_test リポジトリ](https://github.com/h-kitagawa/plext_test) で検討を始めました．
まだ説明は書いていませんが，，test-yoko.pdf, test-tate.pdf で plext 未読み込み時（黒），ASCII 版 plext 読み込み時（赤），そして私の改善案（青）の挙動を比較しています．

**Comment by aminophen** [comment]
> plext_test リポジトリ で検討を始めました．

ありがとうございます。一貫してベースラインが基準となっているので、明快だと思います。ただ、私は慣習については全く知りませんので、特に縦組みの z 指定時など、詳しい方のご意見を聞きたいです。

**Comment by aminophen** [comment]
「周囲の和文ベースラインにそろえる」とすることについてですが、t の場合と z の場合は欧文は“向きが同じ”なので、ベースラインの場所が異なることに違和感を覚えます。z の場合だけとりだした画像の Top と Bottom がこの違和感に該当します。

![tate-z-tabular](https://cloud.githubusercontent.com/assets/9957466/13346663/220859bc-dcab-11e5-9c92-0dec5ea3108b.png)

＃ 個々を取り出すと気になるケースはほかにも出てくるのかもしれませんが、これは？と思ったので挙げてみました。

**Comment by h-kitagawa** [comment]
> 「周囲の和文ベースラインにそろえる」とすることについてですが、t の場合と z の場合は欧文は“向きが同じ”なので、ベースラインの場所が異なることに違和感を覚えます。

それには私も同意します．
試しに，t, b 指定時に欧文ベースラインを基準にするようにすると次のようになります．
（c 指定時や数式中の場合はまだこちらのソースがまともではありません）
![tabular-tz-alph](https://cloud.githubusercontent.com/assets/3954552/13348569/a8821d3c-dcb7-11e5-8eba-93be55c39d3b.png)
ただ，こちらだと最初／最後が横罫線のときが逆に気になってしまいます．

**Comment by aminophen** [comment]
> 試しに，t, b 指定時に欧文ベースラインを基準にするようにすると次のようになります．
> ただ，こちらだと最初／最後が横罫線のときが逆に気になってしまいます．

図は欧文 LaTeX (pdfLaTeX) で tabular に t, b 指定したときのものです。

![pdflatex-table-hline](https://cloud.githubusercontent.com/assets/9957466/13353742/9c3069f4-dcd9-11e5-9f27-702c44d483af.png)

plext の縦組 z 指定＝これを90度回したもの、と仮定すれば、新しいもののほうが納得できると思いました。ただ、同じ論理でいくと縦組 t 指定もやはり欧文ベースライン基準になりますね。

**Comment by h-kitagawa** [comment]
いろいろ悩んでいますが，明確にしないといけないこととして，以下の 2 つがあると思います：
- 「[t] 指定で先頭が罫線だった時は罫線がベースラインの位置に来る」と pLaTeX で言った場合，
  その「ベースライン」は和文ベースラインと欧文ベースラインのどちらを指すのか？
- pTeX の「文中数式モード内のものが一切がベースライン補正される」仕様は適切か？
  
  例えば `$\hbox{あいうabc}$` 中の「abc」は二重にベースライン補正がかかることになり，私は違和感を覚えています．「数式中の明示的なボックス」についてはオフにしてもいいのでは，と考えてみたり．
  tabular 環境では，「縦組中の <z>」「縦数式中の <t>」などで罫線があり/なしの場合の違いにこの問題が関わってきます．

**Comment by aminophen** [comment]
- ベースラインは迷い中です…
- pTeX の挙動については TL2016 の source freeze が迫っているので急がないといけませんが、たしかに数式中の明示的な \hbox{} にもベースライン補正が効くのは違和感があります。[qa:54286](http://oku.edu.mie-u.ac.jp/~okumura/texfaq/qa/54286.html) と [qa:54294](http://oku.edu.mie-u.ac.jp/~okumura/texfaq/qa/54294.html) も似たようなことでしょうか。

**Comment by aminophen** [comment]
> plext.sty の有無で tabular の垂直位置が変わる

[plext.sty の改善案](https://github.com/h-kitagawa/plext_test)の件ですが、ここだけで議論するよりフォーラムにかけたほうがよいのではないかと思います。pTeX のパッチも既に TL16 pretest に入っているわけですし、この Issue を立てたときよりはいくぶん議論しやすくなったとも思いますが、いかがでしょう？

**Comment by h-kitagawa** [comment]
> plext.sty の有無で tabular の垂直位置が変わる

すみませんが，最近多忙のため p(La)TeX  in TL16 への追従や思考の整理ができていません．
最悪，7月末まで　寝かせておくことになると思います．

**Comment by aminophen** [comment]
h-kitagawa さんをお呼び立てしてしまったようで、すみませんでした。community やその中の個人で抱え込みがちだと長続きしませんので、ゆっくりとオープンに議論できればよいなと思っています。

**Comment by aminophen** [comment]
texjporg/platex#24 に移行することにします。
