### ISSUE TITLE
文字コードについて

### ISSUE THREAD

**Issue by aminophen** [texjporg/ptex-texmf#5]
#1 から派生して，別の Issue として登録します。

2016/02/01 に e-pTeX に新設された \epTeXinputencoding プリミティブを使えば，たとえば

``` tex
\ifx\epTeXinputencoding\undefined\else
\epTeXinputencoding utf8\fi
```

のようなコードを各 cls や sty の冒頭に埋め込むことで，全ファイルを UTF-8N に統一することができるようになりました。これにより，文字コードについて現状の ISO-2022-JP のほかに UTF-8N も選択できる可能性が広がりました。

UTF-8N に変換した場合のメリットは
- GitHub Web インターフェースや svn repository で見やすい
- 世界的には UTF-8N が大半とみられる
- ctan2tds の自動化にも載せられる？

一方，留意すべきこととしては
- TeX Live 2016 以降の e-pTeX を必要とする
  - それ以前の環境でも \ifx ... さえ付いていればエラーは出ない。しかし，「Windows で文字コード推定を OFF にしている場合」または「文字コード推定がない Unix で内部コードが UTF-8 以外の場合」または「e- 拡張されていない pTeX の場合」に処理不能。
  - 「バイナリは更新せずにマクロだけ更新する人」がいた場合も上と同じ。
- 今後二度と文字コードを UTF-8(B,N) 以外に変換してはいけない（追記：ISO-2022-JP は可）。
  - 文字コードだけ変換しても \epTeXinputencoding utf8 が残っているので，TeX Live 2016 以降の e-pTeX なら逆に文字化けの原因になる。
  - 一方，TeX Live 2015 以前なら \ifx ... のおかげでスキップされるので，ISO-2022-JP に変換したものが動作すると思われる。

1点目は，少なくとも TeX Live 2016 リリースまでは ISO-2022-JP を維持しなければならないことを意味します。2点目は「ユーザサイドで好きな文字コード（SJIS，EUC）に変換して使う自由を禁じる」ということです。

TeX Live 2016 以降も ISO-2022-JP を維持するのがよいでしょうか，それとも UTF-8N に変換するのがよいでしょうか。

**Comment by kmaed** [comment]
反応遅くてごめんなさい．結局何が最善なのでしょうかね．個人的には問題なさそうならば UTF-8N でいいのでは，という感じです．

ところで，まだ実際に e-pTeX をビルドして試していなくて恐縮なのですが，

> 文字コードだけ変換しても \epTeXinputencoding utf8 が残っているので，TeX Live 2016 以降の e-pTeX なら逆に文字化けの原因になる。

これはそうなんですか？ 以前出ていた [ZR さんの記事](http://qiita.com/zr_tex8r/items/beda5a7702b84409436e)によると，-kanji=utf8 でも JIS は読み込めるということでしたが．

**Comment by aminophen** [comment]
> -kanji=utf8 でも JIS は読み込めるということでしたが．

JIS だけは正常に読めます。ほか（Shift-JIS か EUC）に変換して使おうとすると読めなくなります。文字コード指定の優先順位は[ここ](http://abenori.blogspot.jp/2016/02/e-ptexeptexinputencoding.html)に書かれているとおりで，\epTeXinputencoding は優先順位 1. の段階に入るようです（従来は guess や -kanji にまわっていたはずが，\epTeXinputencoding で固定されてしまう）。よって，「Shift-JIS や EUC にしない限り問題ない」という言い方がより適切でした。

**Comment by kmaed** [comment]
あっ，既にあべのりさんが書かれていましたか．お手数おかけしました．

Shift_JIS や EUC-JP に変換することは（よくわかっていない人が変なことをしない限り）普通はないと思うので，あまりこの点は気にしなくてよいように思います．

残る問題は結局のところ「古いエンジンのままで pLaTeX だけを最新にしたい人がいるだろうか」ということだけなのでしょうが，実際問題としているんですかね．古いエンジンのままにしなければならない人は，過去のものと全く同一の出力が保証されないと困る人のはずなので，pLaTeX だけを最新にするという状況はまず考えられない……，と思うのですが，何か例外はありえるのでしょうか．

追記：メールを読み返してみたら，富樫さんがそういう状況を想定しておいた方がよいと書かれていましたね．つまり，システムの更新が不可能だけれどもマクロの追加は可能な場合ですか．うーん，どうしたものでしょうか．

**Comment by aminophen** [comment]
> 「古いエンジンのままで pLaTeX だけを最新にしたい人がいるだろうか」

私は頻繁にバイナリ＋マクロを丸ごと更新するので考えにくいのですが，一つの見方として：「便利そうなマクロが落ちていたら拾ってくる人」は多いと思います。そのとき「これはいま持っている××年の pTeX で動くだろうか」とか「組版結果に悪影響はないだろうか」と立ち止まる人が果たしているだろうかと考えると，少ないと思います。ただ，これが pLaTeX にまで当てはまるかどうかはわかりません。

追記について：

> システムの更新が不可能だけれどもマクロの追加は可能な場合

これを考え始めると，永久に ISO-2022-JP 以外に変更できなくなってしまう気がします。仮に「○○年以上経ったシステムは切り捨ててよい」とする場合も，期間の判断が難しいです。

**Comment by aminophen** [comment]
> UTF-8N に変換した場合のメリットは (略) ctan2tds の自動化にも載せられる？

と書いたのですが，そもそも ctan2tds を使うための条件は「すべてのファイルが配布できる状態で CTAN にあること」という認識であっていますでしょうか。もしそうであれば，ISO-2022-JP でも全ファイル（tex/ 以下の .cls, .sty や doc/ 以下の .pdf も含む）が生成していれば OK なのでしょうか。

**Comment by abenori** [comment]
> \epTeXinputencoding は優先順位 1. の段階に入るようです

違います．\epTeXinputencodingが解釈された段階で，現在のファイルの文字コードを指定されたものに切り替えます．それ以前の文字コードはptexencによって決定されたものが使われます．北川君のテストをみてもらうとわかりやすいかと思います．

**Comment by aminophen** [comment]
テストは拝見しました。そのうえで，今回の話は

> コードを各 cls や sty の冒頭に埋め込む

という条件付きのつもりで，その場合は（内部処理はともかく）挙動の上では優先順位 1. とみなして差し支えないと思っていました。
