### ISSUE TITLE
CTAN 投稿

### ISSUE THREAD

**Issue by kmaed** [texjporg/ptex-texmf#7]
しばらく放置気味ですいませんでしたが，そろそろ TeX Live 2016 に入れるならば動き出すべきかと思います．うまくまとめて CTAN に上げることを目指しましょう．

**Comment by aminophen** [comment]
フォーマットの日付を 2016/04/17 に上げてみました（とりあえず今から一週間後です）。また、それに合わせて platexrelease のタグを #4 に従い「今回 texjporg が加えた変更点すべて」に付けました。
- `fmtutil --byfmt platex` で `pLaTeX2e <2016/04/17> (based on LaTeX2e <2016/03/31>)` が正しく作成できると思います。
- フォーマットを再作成しなくても、以下のような文書なら「あたかも platex.fmt を 2016/04/17 版で作り直したかのような pLaTeX」が動作します。つまり、いまの TeX Live 2015 frozen の環境に platexrelease.sty さえ取ってくれば、新しい pLaTeX と同じ動作となります。

``` tex
\RequirePackage[latest]{platexrelease}
\documentclass{jarticle}
```

**Comment by kmaed** [comment]
試してみました．うまくいっているように見えます．uptex-texmf も含めて，なるべく色々テストしてみようと思います．

TeX Live 2016 pretest で試していますが，platexrelease を読むと

```
Package platexrelease Warning: Version of `latexrelease' is newer than
(platexrelease)                what `platexrelease' knows.
```

という警告が出ます．\p@known@latexreleaseversion が 2015/01/01 であるのに対して，\latexreleaseversion が 2016/03/31 であるためのようです．

**Comment by aminophen** [comment]
> 警告が出ます．

実装したときの記憶が正しければ、わざと警告コードを入れた気がします。

警告が出るのは「latexrelease が新しすぎて platexrelease が把握できていない場合」です。LaTeX 20150101 と LaTeX 20160331 の間のカーネルの変更点と pLaTeX カーネルが衝突している箇所がなければ、plvers.dtx の当該部分を 2015/01/01 から 2016/03/31 に上げることができます。

 # ZR さんが昔フォーラムでやっていた作業の続きをサボっているのを忘れていました…

**Comment by kmaed** [comment]
latexrelease.sty から 2015/01/01 よりあとのものを引いてみます．

```
141:\IncludeInRelease{2015/10/01}{\luatexluafunction}
142-                             {LuaTeX (prefixed names)}%
--
344:\IncludeInRelease{2016/03/31}%
345-                 {\@ovhlinetrue}%
--
430:\IncludeInRelease{2015/10/01}{\textcommabelow}{comma accent}%
--
439:\IncludeInRelease{2016/02/01}{\textcommaabove}{comma above}%
--
727:\IncludeInRelease{2015/10/01}%
728-                 {\bx@ZZ}{Extended float list}%
--
1522:\IncludeInRelease{2015/10/01}
1523-                 {\e@ch@ck}{Extended Allocation (checking)}%
--
1592:\IncludeInRelease{2015/10/01}
1593-                 {\newinsert}{Extended \newinsert}%
--
1647:\IncludeInRelease{2015/01/20}{\loggingall}{etex tracing}%
--
1687:\IncludeInRelease{2015/01/20}{\tracingnone}%
1688-                             {turn off etex tracing}%
--
2121:\IncludeInRelease{2015/10/01}
2122-                 {\newluafunction}{LuaTeX}%
--
2337:\IncludeInRelease{2016/02/01}%
2338-  {\xe@alloc@intercharclass}{Start of XeTeX class allocator}%
--
2360:\IncludeInRelease{2016/02/01}%
2361-  {\XeTeXintercharclasses}{XeTeX character classes}%
```

ミスっていなければ12箇所ですかね．

**Comment by aminophen** [comment]
ありがとうございます。pLaTeX のフォーマットと衝突するものはないように見えます。plvers.dtx を更新しておきます。uptex-texmf も今日の変更分をパッチしてみます。

**Comment by aminophen** [comment]
ptex-texmf / uptex-texmf ともに更新しました。ちなみに uptex-texmf は今のところ ptex-texmf の dtx の変更をパッチにして素朴に当ててみて、reject されたところ（＝おもにバージョン番号のところ）を手動で当てなおし、ltx や sty を再生成することでまかなっています。

**Comment by aminophen** [comment]
platexrelease について迷っているので：

latexrelease はパッチをあてる必要がない場合などには敢えてパッチをあてないように、`\endinput` で読み込みを中断させるコードがあります。しかし、これを platexrelease でそのまま使ってしまうと例えば

``` tex
% platex.fmt が pLaTeX2e 2016/04/17 (based on LaTeX2e 2016/03/31) の状態で
\RequirePackage[2015/01/01]{latexrelease} % この行がなければ問題なし
\RequirePackage[2016/04/17]{platexrelease} % 2016/04/16 以前なら問題なし
\documentclass{jarticle}
\def\eminnershape{\gtfamily\scshape}
\begin{document}
あa{\em いb{\em うc}えd}おe
\end{document}
```

こうすると、master branch の platexrelease.sty は日付がフォーマットと同じなので読み込みを中断します。しかし、その手前で既に latexrelease がパッチをあててしまっているため不都合が生じます。

platexrelease の読み込みを中断せずに必ずパッチをあてるようにした新しいものを、exp_2ekernel branch に置いてみました。こうすると latexrelease → platexrelease の順で `\RequirePackage` すれば別々の日付を指定するという使い方が可能になるのですが、逆に platexrelease 単独で使った場合に無用にパッチをあてることになります（害はないはずだが処理量が増える）。害がなさそうなら新しいほうに変えようかと思います。

**Comment by aminophen** [comment]
> latexrelease → platexrelease の順で \RequirePackage すれば別々の日付を指定するという使い方が可能になる

やっぱりこういう使いかたを許すとそれはそれで考えることが増えてしまうので、master のものを現状維持することにします。あまりここだけで議論しているのはよくない気がしますし、PDF ドキュメントを rebuild したら一旦リリースするのはどうでしょうか。

**Comment by kmaed** [comment]
すいません，README の整備をしたいと思っていたのですが，滞っています．いずれにせよ，早めに pretest に入れてテストをしてみるべきだと思います．

**Comment by aminophen** [comment]
ひとまず ptex-texmf も uptex-texmf も `git tag 2016/04/17` してみました。GitHub だと Release タブに反映されるのですね。Release Note も付けてみました。

**Comment by kmaed** [comment]
ありがとうございます．では早速 CTAN に上げてみましょうか．

ptex-texmf は ptex-texmf を上書きすればよいのでしょうが，uptex-texmf はどうするべきでしょうか．

**Comment by aminophen** [comment]
uptex-texmf はいままでなかったのですね。新しくつくってしまってよいのではないでしょうか。

（ひとまず CTAN にあげたとしても今のところ ctan2tds にスクリプトが無いので，その先は devel で調整していただくことになると思います）

**Comment by kmaed** [comment]
とりあえず ptex-texmf は upload してみました．次は uptex-texmf です．

**Comment by kmaed** [comment]
いくつかアップロードするファイルについての問題が指摘されたので，私の方で対処してみます (CTAN に上げるのは初めてなので不慣れです)．

それから，考えてみれば当たり前なのですが，メンテナについての問題も指摘されたので調整します．（私は今日も来週も通常通り出勤ですが）世間的には連休なので，もしかしたら少し時間がかかるかもしれません．

**Comment by aminophen** [comment]
すみません、お手数おかけします。

**Comment by kmaed** [comment]
ファイルについて，自分だけだと結構大変な気がしてきたので，指摘された点をここに転載しておきます．

```
 (1) http://mirror.ctan.org/help/ctan/CTAN-upload-addendum.html#flatstructure
     Your upload is _very_ deeply nested, in fact it seems to be
     a true TDS structure, which should not be the case in the
     "unpacked" part of the archive.
     The problem is that, given the complexity of your system,
     I cannot see how this can be improved in the sense of
     "flattening" the layout.

 (2) http://mirror.ctan.org/help/ctan/CTAN-upload-addendum.html#noauxfiles
     ./doc/ptex/eptex/rmc10.600pk should probably be deleted?

 (3) http://mirror.ctan.org/help/ctan/CTAN-upload-addendum.html#uniquefilenames
     http://mirror.ctan.org/help/ctan/CTAN-upload-addendum.html#noduplicatefiles
     There are great numbers of such files, which can probably
     not be helped ... (?)

 (4) http://mirror.ctan.org/help/ctan/CTAN-upload-addendum.html#nogeneratedfiles
     If any of
                  ./doc/ptex/eptex/styles.sty
                  ./tex/platex/base/tbook.sty
                  ./tex/platex/base/jt1mc.fd
                  ./tex/platex/base/tsize10.clo
                  ./tex/platex/base/plext.sty
                  ./tex/platex/base/jreport.cls
                  ./tex/platex/base/ascmac.sty
                  ./tex/platex/base/jreport.sty
                  ./tex/platex/base/tbook.cls
                  ./tex/platex/base/treport.sty
                  ./tex/platex/base/platexrelease.sty
                  ./tex/platex/base/jt1gt.fd
                  ./tex/platex/base/tascmac.sty
                  ./tex/platex/base/tsize12.clo
                  ./tex/platex/base/treport.cls
                  ./tex/platex/base/jarticle.sty
                  ./tex/platex/base/tbk10.clo
                  ./tex/platex/base/jbk11.clo
                  ./tex/platex/base/plnews.cls
                  ./tex/platex/base/nidanfloat.sty
                  ./tex/platex/base/jbk10.clo
                  ./tex/platex/base/oldpfont.sty
                  ./tex/platex/base/tarticle.sty
                  ./tex/platex/base/jsize10.clo
                  ./tex/platex/base/tarticle.cls
                  ./tex/platex/base/tsize11.clo
                  ./tex/platex/base/jsize11.clo
                  ./tex/platex/base/jbook.cls
                  ./tex/platex/base/tbk11.clo
                  ./tex/platex/base/jsize12.clo
                  ./tex/platex/base/jbk12.clo
                  ./tex/platex/base/jy1gt.fd
                  ./tex/platex/base/tbk12.clo
                  ./tex/platex/base/jbook.sty
                  ./tex/platex/base/ptrace.sty
                  ./tex/platex/base/jltxdoc.cls
                  ./tex/platex/base/jarticle.cls
                  ./tex/platex/base/jy1mc.fd
     can be generated from any of the .dtx files, those
     "generated" files should be left out of the "unpacked"
     arrangement.

 (5) Finally:
     http://mirror.ctan.org/help/ctan/CTAN-upload-addendum.html#urls
     There are a number of these "tex-archive" links
     (ftp://cam.ctan.org/tex-archive does not even exist any more!).
     We would be grateful if you could replace them with the
     http://mirror.ctan.org/... or the http://www.ctan.org/pkg/...
     variants.
```

(4) は注意事項をちゃんと読んでいない私が悪いです．
(2) は一時ファイルならば削除すればよいですが，どうなんでしょう．

(5) は doc/ptex/base/INSTALL のことだと思いますが，ASCII のファイルそのままだと思うので，どうしましょうか．

(1) と (3) はどうしたものでしょうか．歴史的なファイルも含めて，整理できるとよいのですが．元々 CTAN にある ptex.tds.zip が参考になるのかな．

**Comment by h-kitagawa** [comment]
とりあえず：

> (2) http://mirror.ctan.org/help/ctan/CTAN-upload-addendum.html#noauxfiles

rmc10.600pk は削除しても構わないです（rmc10.{mf,tfm} もゆくゆくは削除する方針です）．

**Comment by aminophen** [comment]
h-kitagawa さん、ありがとうございます。

> 元々 CTAN にある ptex.tds.zip が参考になるのかな．

私も CTAN に upload したことがないのでよくわかりませんが、元の ptex.tds.zip を (1)-(5) に照らし合わせてみると、どうみても CTAN の方針に合致しているとは思えません… 当時のことはわかりませんが、文字コードを ISO-2022-JP にしておくために無理をとおしたのでしょうか。

tds.zip 単体で upload されている例をさがそうとしているのですが、latex-base なども案外フラットに置かれていて、まだ見つけていません。参考になりそうな例をご存知の方はいらっしゃいますか？

（とはいっても ... whereas we do not ac­cept up­loads that con­tain noth­ing but a .tds.zip file. という一文があるので、そもそも ptex.tds.zip を手本にしてはいけないということでしょうね…）

**Comment by kmaed** [comment]
> whereas we do not ac­cept up­loads that con­tain noth­ing but a .tds.zip file. という一文がある

そうなんですよね．よくわからないです．整理できるならば整理してしまった方が早いような気がするのですが，大変かな．

https://www.ctan.org/tex-archive/macros/latex/contrib/latex-tds 

みたいな感じに .tds.zip をいくつか作るか，パッケージ自体をいくつかに分割するのがよいのかな（？）．いずれにせよ，CTAN 管理者に把握できる程度には分ける必要があるように思います．例えば，pbibtex と fonts は分割すると良さそう？ uptex-texmf のことも合わせて考えましょう．

（と書いたのですが，latex-tds は別にある各パッケージを zip で固めただけかも．やっぱりパッケージを分けないとだめ？）

**Comment by aminophen** [comment]
uptex-texmf はすみません、全然変更していないファイルも全てリポジトリに入れてしまったのでややこしくしてしまったと思います。ptex も uptex も、fonts や pbibtex はマクロと関係ないので、ドキュメント込みで独立させるほうに一票です。

**Comment by kmaed** [comment]
元々 ptex-texmf はごった煮な感じがしていたので，これを機に分割するのもよいのではと思っています．その場合，元から CTAN にある ptex-texmf との関係をどうするかは，ちょうどメンテナの件でアスキーにメールを書いているところなので，私の方で聞いておこうと思います．

**Comment by aminophen** [comment]
リリースの話の途中で申し訳ありませんが、コード自体の件で：ptrace.sty は tracefnt.sty なしには使えない（分かりにくいエラーが出る）ので、冒頭に `\RequirePackageWithOptions` を加えました。

**Comment by aminophen** [comment]
めでたく CTAN 投稿と TeX Live への収録が完了したので、close とします。

CTAN への投稿について[教訓](https://github.com/texjporg/ptex-texmf/issues/7#issuecomment-215615856)が得られたのでよかったです ^^;)
