### ISSUE TITLE
パッケージ分割

### ISSUE THREAD

**Issue by kmaed** [texjporg/ptex-texmf#8]
CTAN にアップロードする際に「あまりに複雑すぎる」と言われてしまったので，ptex-texmf をいくつかに分割することを提案したいと思います．管理上も，現状ではマクロ (plain, LaTeX), フォント，pbibtex のファイルが同居していて，ディレクトリもそれぞれ分かれているので全貌が見えづらいですが，分割すると見やすくなると思います．

締切が迫ってきてしまったので急いでやらなければなりませんが，例えば以下のようにするのはどうでしょうか．それぞれの内容は名前から明らかだと思います．
- ptex-base
- platex-base
- pbibtex-base
- ptex-fonts

現状のまま ptex-texmf リポジトリで管理して，CTAN に上げるときだけ分けるという方法もありますが，リポジトリ自体も分割してしまった方がやりやすいでしょう．異論がなければ実行しようと思います．

**Comment by aminophen** [comment]
> リポジトリ自体も分割してしまった方がやりやすいでしょう．

異論なしです。分割した場合は、極力フラットな配置にしたほうが upload の負担が減りそうですね。

今ある ptex-texmf は各々へのポインタおよび履歴としてだけ残しておく（ほぼ空っぽにする）？

**Comment by kmaed** [comment]
> 今ある ptex-texmf は各々へのポインタおよび履歴としてだけ残しておく（ほぼ空っぽにする）？

全て残してもよいですし，紛らわしいならば README.md 以外を消してしまってもよいと思います．
