### ISSUE TITLE
hyphen.cfg -> (u)platex.ini

### ISSUE THREAD

**Issue by norbusan** [texjporg/ptex-texmf#9]
皆さん
今のところ、TeX Liveの中、(u)platexの特別のhyphen.cfgが使われている。普通のhyphen.cfgの差は：

```
+%% ( written by Tono san ) 
+%%
+\ifx\platexDUMP\@undefined\else
+    \advance\last@language\@ne
+    \edef\platexBANNER{\the\toks8 \the\last@language\space language(s)\space}%
+    \advance\last@language\m@ne
+\fi%%
+%%
```

特別のhyphen.cfgのかわりに、上の様なコードを(u)platex.iniに入れる提案です。

とりあえず新しいbranchを作成しました：move-hyphen-adapation-to-iniを見て意見をお願いします。

ノルベルト

**Comment by aminophen** [comment]
babel から毎回 hyphen だけ import していたのが簡単になるのであれば、私は賛成です。ただ、いままでは確か import script があったと思いますが、それを TeX Live サイドでやめてもらう必要もあると思います。

**Comment by norbusan** [comment]
import scriptの存在をしりませんでした。。。僕が見たのは、角藤先生がいつも手で変更してcommitしました。TeX Live側から問題ないと思います。

**Comment by aminophen** [comment]
> 角藤先生がいつも手で変更してcommitしました。

このあたりは私は知りませんが、
- [devel:223] Re: GitHub 内にtexjporg Organizationを作りました

の中で角藤先生がおっしゃっていたことを心配していました。

（Update: closed な ML の発言のため内容削除。）

**Comment by norbusan** [comment]
なるほど。。。でも、このスクリプトが使う必要さがなくなったら、Karlは絶対に反対しません（笑）

**Comment by aminophen** [comment]
たぶんいままで platex.ini を勝手に変更できなかったから、workaround として import script が作られたのだと思います。だから、私は新しい (u)platex.ini にコードを入れることに賛成です。

**Comment by kmaed** [comment]
入れることで何か問題が解決するのならば，入れればよいと思います．platex-base と uplatex-base は既に CTAN に投稿してしまっていますが，更新すればよいことです．

**Comment by aminophen** [comment]
いくつか CTAN に反映されていることを確認しました。ありがとうございます。
- https://www.ctan.org/pkg/platex-base
- https://www.ctan.org/pkg/uplatex-base
- https://www.ctan.org/pkg/ptex-fonts
- https://www.ctan.org/pkg/uptex-fonts
- https://www.ctan.org/pkg/uptex-base
- https://www.ctan.org/pkg/pbibtex-base

ptex-base だけ未確認です。

**Comment by kmaed** [comment]
> ptex-base だけ未確認です。

ちょっと事情があって遅れています．もう少しだけお待ち下さい．

**Comment by aminophen** [comment]
hyphen.cfg の件をテストしているのですが
- カレントディレクトリに「普通の hyphen.cfg 」を置く
- platex.ini にノルベルトさんの変更を加える

としてフォーマットを作成すると

```
pLaTeX2e <2016/04/17> (based on LaTeX2e <2016/03/31>)
81 language(s) loaded.
```

となります。これだとどのバージョンの babel が読まれたかわからないです。`\the\toks8` は hyphen.cfg のなかの `\toks8{Babel <3.9r> and hyphenation patterns for }%` を取得する予定にみえますが、実際に走らせてみると取得できていません。

```
LaTeX2e <2016/03/31>
Babel <3.9r> and hyphenation patterns for 81 language(s) loaded.
```

並みの情報量を出すにはどうすればよいのでしょう？

**Comment by kmaed** [comment]
latex.ltx の最後の方に

```
\toks8{}
```

があるので，\toks8 からは取得できないようです．platex.ltx 中で \input plcore.ltx する前の \everyjob を見ると

```
> \typeout {\fmtname \space <\fmtversion >}\typeout {Babel <3.9r> and hyphenati
on patterns for 81 language(s) loaded.}.
l.49 \showthe\everyjob
```

となっているので，うまくやればここから取得できるかもしれません．

**Comment by aminophen** [comment]
なるほど、少しわかってきました。試しに platex.ltx の `\input latex.ltx` の直後に

``` tex
\edef\platexBANNER{\the\everyjob}% save LaTeX banner
```

を入れて、platex.ini のほうで `\input platex.ltx` のあとに

``` tex
\begingroup  \makeatletter%
    \def\parse@everyjob#1{\expandafter\parse@@everyjob#1}%
    \def\parse@@everyjob#1#2#3#4{#4}%
    \edef\platexTMP{%
        \the\everyjob\noexpand\typeout{\parse@everyjob{\platexBANNER}}%
    }%
    \everyjob=\expandafter{\platexTMP}%
    \edef\platexTMP{%
        \noexpand\let\noexpand\platexBANNER=\noexpand\@undefined
        \noexpand\let\noexpand\dump=\noexpand\platexDUMP
        \noexpand\let\noexpand\platexDUMP=\noexpand\@undefined
        \noexpand\everyjob={\the\everyjob}%
    }
    \expandafter
\endgroup \platexTMP
```

とやればソレっぽく表示はされます。もう少し考えてみます。

**Comment by aminophen** [comment]
最終的には LaTeX のバナーを保存した制御綴を `\@undefined` にしたいことを加味して微妙に上のコメントを書き変えました。これならいけそうな気がしますが、いかがでしょうか？

**Comment by kmaed** [comment]
> \def\parse@@everyjob#1#2#3#4{#4}%

なるほど，うまいですね．さすが TeX 言語使いです．私のところではちゃんと動いています．

単に名前の問題ですが，\parse@everyjob よりも \parse@BANNER とかの方がよいかもしれないです．

**Comment by aminophen** [comment]
確認いただきありがとうございます。名前もおっしゃるとおり \parse@BANNER の方がよさそうなのでそのようにして platex repository に push しました。可能ならば pLaTeX 用の特別の hyphen.cfg を TeX Live 側でやめていただけるとよいと思います。

**Comment by kmaed** [comment]
Karlさんから platex.ini についての返事がこないので少し待っていたのですが，そろそろ CTAN に上げてもいいかもしれないですね．

**Comment by aminophen** [comment]
CTAN にあげるのであれば、(u)pLaTeX のフォーマット日付を上げたほうがいいと思います。日付を上げたうえでフォーマット再作成とバナー表示をテストいただき、(u)platex.pdf / (u)pldoc.pdf をリビルドしないといけません（どなたかにお願いしてよろしいですか？）。

新しい platex.ini / platex.ltx のセットなら、仮に特別の hyphen.cfg が消されず残っていてもバナーは今回の変更の期待どおりになるはずですので、大きな問題は起きないと思います。

**Comment by norbusan** [comment]
Karlからの返事：

> That would be a great outcome, one way or another. 

ですが、他にも書いていました：

> What concerns me is that this is using internal babel control sequences 
> and assuming \the\toks8.  I don't look forward to figuring out what
> happened when (u)platex format rebuilding fails in some random way.
> Oh well, I guess I worry too much.                                              
> 
> Stray idea: is this info actually needed?  What if we simply don't
> output anything about this in (u)platex?

という返事でした。

**Comment by aminophen** [comment]
> What concerns me is that this is using internal babel control sequences and assuming \the\toks8.

この件については OK です。昨日 commitしたものは \toks8 を使わない better なコードです。[9620dd8](https://github.com/texjporg/platex/commit/9620dd8d58b8ec8c3449b9ba7d07732203c7d750) ですから、安心して特別の hyphen.cfg をやめることができます。

**Comment by norbusan** [comment]
なるほど、すみません、気がついていませんでした。
ですから、いつでもアップロードしていいと思います。その後僕は別のhyphen.cfg処分します。

**Comment by aminophen** [comment]
角藤さんに hyphen.cfg を [r41026](http://tug.org/svn/texlive?view=revision&revision=41026) で処分していただいたので完了とします。
